intel/dffml

CHANGELOG.md, dffml/source/file.py, tests/source/test_file.py
Added condition for opening and closing gzip files
=> dffml: source: file: Added Gzip support

.ci/run.sh, .travis.yml, CHANGELOG.md, dffml/source/file.py
=> travis: Ensure additions to CHANGELOG.md

CONTRIBUTING.md, README.md
Didn't add the gitter badge in this as did already in #67. References #60.
=> Added Contributing to README.md

CHANGELOG.md, README.md
=> README: Add gitter badge

.ci/run.sh, CHANGELOG.md
=> ci: Plugin tests no longer always exit cleanly

CHANGELOG.md, dffml/df/types.py, dffml/operation/output.py, docs/community.rst, docs/concepts/index.rst, docs/index.rst, docs/plugins/dffml_model.rst, docs/plugins/dffml_operation_implementation.rst, docs/plugins/dffml_source.rst, docs/plugins/index.rst, docs/usage/integration.rst, model/tensorflow/README.md, model/tensorflow/dffml_model_tensorflow/model/dnn.py, model/tensorflow/tests/test_dnn.py, scripts/docs.py, scripts/docs.sh, scripts/docs/care, scripts/docs/templates/dffml_model.rst, scripts/docs/templates/dffml_operation_implementation.rst, scripts/docs/templates/dffml_source.rst, scripts/skel/model/README.md
* Add spec field to Definition to allow for documenting of complex types
=> docs: Plugins

CHANGELOG.md, dffml/df/base.py, dffml/df/memory.py, dffml/util/asynchelper.py, docs/api/index.rst, docs/api/util/asynchelper.rst, docs/api/util/index.rst, docs/conf.py, docs/index.rst
=> util: asynchelper: aenter_stack method

CHANGELOG.md, dffml/source/csv.py, dffml/source/file.py, tests/source/test_csv.py, tests/source/test_file.py
=> WIP: source: csv: Enable setting repo src_url 

CHANGELOG.md, dffml/source/csv.py, dffml/source/file.py, tests/source/test_csv.py, tests/source/test_file.py
=> Revert "WIP: source: csv: Enable setting repo src_url "

CHANGELOG.md, dffml/source/file.py, dffml/source/json.py, dffml/util/testing/source.py, examples/source/test_custom_sqlite.py, tests/source/test_csv.py, tests/source/test_file.py, tests/source/test_json.py, tests/test_cli.py
This PR hopes to add a feature where we can include a label for the data source that can be used to add a version of the data set as well. This will help in having multiple versions of the dataset that can be trained.
=> Label Source feature

CHANGELOG.md, dffml/util/entrypoint.py, tests/test_cli.py
* Loaded classes will otherwise share ENTRY_POINT_LABEL unless
subclassed from.
Fixes: #100
=> util: entrypoint: Subclasss from loaded class

lgtm.yaml
=> lgtm: Add lgtm.yaml

docs/usage/installation.rst
=> docs: installation: Re-add info on docker

dffml/util/entrypoint.py
=> util: entrypoint: Correct loaded class name

CHANGELOG.md, Dockerfile
=> Dockerfile: Update pip

CHANGELOG.md, CONTRIBUTING.md
=> CONTRIBUTING: Add link to community.html

CHANGELOG.md, dffml/df/memory.py
=> df: memory: Fix strict should be True

CHANGELOG.md, docs/index.rst, docs/plugins/dffml_model.rst, docs/plugins/dffml_operation_implementation.rst, docs/plugins/dffml_service_cli.rst, docs/plugins/dffml_source.rst, docs/usage/installation.rst, model/scratch/dffml_model_scratch/slr.py, model/tensorflow/dffml_model_tensorflow/dnnc.py, scripts/docs.py, scripts/docs/care, scripts/docs/templates/dffml_model.rst, setup.py
=> docs: Improve homepage and plugins

HACKING.md
=> docs: HACKING: added logging for testing

CHANGELOG.md, dffml/source/csv.py, tests/service/test_dev.py, tests/source/test_csv.py, tests/test_cli.py
This PR enables setting label and corresponding LabelColumn in CSVSource.
=> Label csv source feature

examples/shouldi/setup.py
=> examples: shouldi: Add dev mode hack

.ci/run.sh, CHANGELOG.md, feature/auth/dffml_feature_auth/feature/definitions.py, feature/auth/dffml_feature_auth/feature/log.py, feature/auth/dffml_feature_auth/feature/operations.py, feature/auth/dffml_feature_auth/version.py, feature/auth/setup.py, feature/auth/tests/test_df.py, feature/git/dffml_feature_git/feature/definitions.py, feature/git/dffml_feature_git/feature/log.py, feature/git/dffml_feature_git/feature/operations.py, feature/git/dffml_feature_git/log.py, feature/git/dffml_feature_git/util/log.py, feature/git/dffml_feature_git/util/proc.py, feature/git/dffml_feature_git/version.py, feature/git/setup.py, model/scikit/setup.py, model/tensorflow/dffml_model_tensorflow/dnnc.py, model/tensorflow/tests/test_dnnc.py, scripts/docs.py, setup.py
* Enforce style in all submodules via ci
Fixes: #173
=> style: Correct style of all submodules

model/scikit/dffml_model_scikit/scikit_base.py, model/scikit/dffml_model_scikit/scikit_models.py, model/scikit/setup.py, scripts/docs.sh
=> model: scikit: Correct entrypoints again

CHANGELOG.md, HACKING.md, dffml/service/dev.py
=> service: dev: List entrypoints

dffml/util/testing/source.py, examples/source/test_custom_sqlite.py, tests/source/test_json.py
=> Fixed TestCases

CHANGELOG.md, dffml/base.py, model/scikit/dffml_model_scikit/scikit_models.py
=> model: scikit: Fix CLI based configuration

README.md
I don't think we need to do #121 after this
=> Added black badge to README

scripts/docs/care
=> docs:source: modify care for mysql source

dffml/util/cli/cmd.py
=> util: cli: JSON serialize enum values

CHANGELOG.md, dffml/model/model.py, dffml/repo.py, model/scikit/dffml_model_scikit/scikit_base.py, model/scikit/tests/test_scikit.py, model/scratch/dffml_model_scratch/slr.py, model/scratch/tests/test_slr.py, model/tensorflow/dffml_model_tensorflow/dnnc.py, model/tensorflow/tests/test_dnnc.py
=> model: Predict only yields repo

CHANGELOG.md, model/tensorflow/dffml_model_tensorflow/dnnc.py
Was renamed DNNClassifierModelContext first init arg from config to features
=> Bug rename init arg in DNNClassifierModelContext

model/tensorflow/dffml_model_tensorflow/dnnc.py
=> WIP: added hidden_layer info to hash of model_dir in tfdnnc

service/http/dffml_service_http/version.py
=> service: http: Version 0.0.2

CHANGELOG.md, dffml/source/source.py
=> source: source.py: Add base_entry_point decorator

dffml/df/memory.py
As per the suggestions of @pdxjohnny
=> Removed notification set memory 

CHANGELOG.md, dffml/cli/dataflow.py, dffml/util/cli/cmds.py, dffml/util/cli/parser.py, tests/util/test_cli.py
=> cli: Remove old operations command code

CHANGELOG.md, tests/test_integration_cli.py
=> tests: integration: Merge memory to csv

dffml/skel/model/README.md, docs/plugins/dffml_model.rst, docs/usage/integration.rst, examples/maintained/cgi-bin/api-ml.py, model/scikit/dffml_model_scikit/__init__.py, model/scratch/README.md, news/origin_master_August_15_2019.txt
=> docs: model: Replaced -features with -model-features

CHANGELOG.md, source/mysql/MANIFEST.in, source/mysql/README.md, source/mysql/dffml_source_mysql/version.py, source/mysql/setup.py, source/mysql/setup_common.py
=> fix : mysql setup

CHANGELOG.md, dffml/service/dev.py
=> service: dev: install: Speed up install of plugins

dffml/service/dev.py, tests/test_integration_cli.py
=> test: service: develop: Run single

CHANGELOG.md, dffml/util/entrypoint.py
=> util: entrypoint: Speed up named loads

CHANGELOG.md, dffml/util/cli/cmd.py, tests/integration/test_models.py
Fixes: #261
Co-authored-by: Saksham Arora <50872172+sakshamarora1@users.noreply.github.com>
=> cli: Fix numpy int* and float* json output

CHANGELOG.md, dffml/base.py, dffml/model/model.py, dffml/source/csv.py, docs/api/base.rst, docs/api/index.rst, docs/plugins/dffml_model.rst, docs/plugins/dffml_source.rst, model/scratch/dffml_model_scratch/slr.py, model/tensorflow/dffml_model_tensorflow/dnnc.py, model/tensorflow/dffml_model_tensorflow/dnnr.py, scripts/docs.py, tests/integration/common.py, tests/integration/test_sources.py, tests/test_base.py, tests/test_cli.py
fixes #207 and
cleans `config` and `arg` methods in `models`
=> WIP : config,args cleanup

.deepsource.toml
Hi,
I'm the founder of DeepSource, and I wanted to suggest using DeepSource for running continuous static analysis on this project. I ran analysis on my own fork of this repo, and found some interesting results (although most of them are in test files — the source code is really clean otherwise!). You can see the results [here](https://deepsource.io/gh/sanketsaurav/dffml/issues/?show_minor=true).
DeepSource is **free forever for open-source**, and is trusted by teams at Uber, NASA, Slack, ThoughtWorks, among many others to ensure their code is free of 600+ security and performance issues, bug risks, and anti-patterns. 
I've added a .deepsource.toml file for this repo, enabling Python and Dockerfile analysis. All you need to do is:
1. [Sign up](https://deepsource.io/signup) on DeepSource …
=> Consider using DeepSource for continuous static analysis

CHANGELOG.md, CONTRIBUTING.md, dffml/cli/cli.py
=> Updates to CONTRIBUTING.md

CHANGELOG.md, dffml/util/asynctestcase.py, tests/integration/common.py, tests/test_cli.py
=> util: asynctestcase: AsyncExitStackTestCase

scripts/docs.sh
=> scripts: docs: Error message when missing sphinx

.ci/run.sh, .github/workflows/testing.yml, CHANGELOG.md, dffml/service/dev.py, tests/service/test_dev.py
=> ci: Enable auto release to PyPi

.ci/run.sh, .github/workflows/testing.yml, CHANGELOG.md
=> ci: Auto deploy docs

CHANGELOG.md, dffml/base.py, model/scikit/dffml_model_scikit/scikit_models.py
=> Add make_config and use in model/scikit

CONTRIBUTING.md
python3.7 -m pip install -e --prefix=~/.local .[dev]
Changed to:
python3.7 -m pip install --prefix=~/.local -e .[dev]
=> Documenetation: contributing: Update CONTRIBUTING.md

CHANGELOG.md, dffml/cli/dataflow.py, dffml/config/config.py, dffml/util/asynchelper.py, dffml/util/data.py, tests/config/test_config_loader.py
=> WIP : ConfigLoader 

dffml/skel/model/REPLACE_IMPORT_PACKAGE_NAME/misc.py, dffml/skel/source/REPLACE_IMPORT_PACKAGE_NAME/misc.py
Removes all instances of args and config.
fixes: #164
=> skel: misc: Replace args and config methods

CHANGELOG.md, dffml/base.py, dffml/cli/dataflow.py, dffml/db/base.py, dffml/db/sql.py, dffml/db/sqlite.py, dffml/df/types.py, dffml/operation/dataflow.py, dffml/operation/db.py, dffml/util/data.py, docs/api/db/base.rst, docs/api/db/index.rst, docs/api/db/sql.rst, docs/api/db/sqlite.rst, docs/api/index.rst, docs/conf.py, docs/usage/integration.rst, setup.py, source/mysql/dffml_source_mysql/db.py, source/mysql/dffml_source_mysql/util/mysql_docker.py, source/mysql/setup.py, source/mysql/tests/test_db.py, tests/db/test_sqlite.py, tests/operation/test_sqlite_query.py
#274 is getting a bit messy. Seeing as @aghinsa has finished the database abstraction, as well as the sqlite and mysql connectors. It's time we merged this. That way work on using these within a dataflow for the integration example can continue to happen in a more organized fashion over in #274
=> Database abstraction with SQLite and MySQL DBs

docs/plugins/dffml_model.rst, docs/usage/integration.rst, examples/maintained/cgi-bin/api-ml.py, model/tensorflow/dffml_model_tensorflow/dnnc.py, model/tensorflow/tests/test_dnnc.py
=> WIP : model : tensorflow : dnnc : change classification to predict

model/tensorflow/setup.py
=> model: tensorflow: Pin to pre 1.15.1

.ci/run.sh, .github/workflows/testing.yml, docs/index.rst
=> ci: Build webui

CHANGELOG.md, service/http/dffml_service_http/routes.py, service/http/docs/api.rst, service/http/tests/test_routes.py
=> service: http: Add file listing

CHANGELOG.md, dffml/df/base.py, dffml/df/memory.py
=> df: memory: Throw OperationException on operation errors

CHANGELOG.md, dffml/feature/feature.py, tests/test_cli.py, tests/test_feature.py
@pdxjohnny checkout the changes that I made !!
thanks
=> feature: Remove evaluation methods

CHANGELOG.md, dffml/source/csv.py, dffml/source/file.py, dffml/source/json.py, dffml/util/testing/source.py, docs/plugins/dffml_source.rst, examples/source/test_custom_sqlite.py, service/http/tests/test_routes.py, source/mysql/tests/test_source.py, tests/integration/test_cli.py, tests/source/test_csv.py, tests/source/test_file.py, tests/test_cli.py
=> sources : change label to tag

CHANGELOG.md, dffml/df/types.py
=> df: types: Add subspec parameter to Definition

dffml/df/memory.py
=> Remove set_items from NotificationSetContext 

CHANGELOG.md, service/http/docs/api.rst
Hi, 
I'm new to dffml, looking to apply to GSOC project "Doctest-able Examples". I was studying the project when I came across the quick first issue so I thought what better way to introduce myself :)
Any advice regarding going about the project would be highly appreciated.
Fixed issue #406 
Thanks
=> Fixed issue #406

.github/workflows/testing.yml
=> ci: Fetch all history for all tags and branches

docs/api/record.rst, docs/tutorials/intro.rst, service/http/docs/api.rst
Hi there!
I am Aryan , and I am looking to apply for the Project "Doctest-able Examples".
I have fixed the issue #417 , hoping to contribute more!
=> Underlined the Text

CHANGELOG.md, docs/contributing/style.rst
Added a note on how to install black and make the required changes in the VSCode editor.
closes #121
=> CONTIRIBUTING: Add note about using black via VSCode

model/scikit/tests/test_scikit_integration.py
the dataset used in `model/scikit/tests/test_scikit_integration.py` is replaced with randomly generated dataset.
references #413 
I have only added code for `TestScikitClassification` class, for keeping pull requests small.
=> add randomly generated data for tests

CHANGELOG.md, dffml/high_level.py, docs/conf.py, docs/contributing/dev_community.rst, docs/contributing/docs.rst, docs/contributing/index.rst, docs/doctest_header.py
=> high level: Example for predict in docstring

CHANGELOG.md, dffml/high_level.py
Added doctestable examples to high_level 
Signed-off-by: Hashim.git <hashimchaudry23@gmail.com>
=> High-level API: Added Doctestable examples.

CHANGELOG.md, dffml/record.py, docs/doctest_header.py
The Record class is still a WIP. I wanted to get a review on the functions before moving on to the next ones.
Signed-off-by: mHash1m <hashimchaudry23@gmail.com>
=> Record: Docstrings and doctestable examples for features and evaluated

CHANGELOG.md, dffml/service/dev.py, tests/service/test_dev.py
=> service: dev: Create fresh archive instead of cleaning

.ci/run.sh, .github/workflows/testing.yml, CHANGELOG.md, dffml/__init__.py, dffml/base.py, dffml/feature/feature.py, dffml/model/__init__.py, dffml/model/model.py, docs/plugins/dffml_model.rst, model/scikit/dffml_model_scikit/scikit_models.py, model/scratch/dffml_model_scratch/slr.py, model/scratch/tests/test_slr.py, model/scratch/tests/test_slr_integration.py, scripts/check_literalincludes.py, scripts/docs.py, tests/source/test_idx.py
=> WIP: Simplify Model API

CHANGELOG.md, dffml/model/model.py, dffml/skel/model/REPLACE_IMPORT_PACKAGE_NAME/misc.py, dffml/skel/model/tests/test_model.py, docs/tutorials/index.rst, docs/tutorials/model.rst
=> docs: Update new model tutorial for simplified API

CHANGELOG.md, dffml/skel/model/REPLACE_IMPORT_PACKAGE_NAME/misc.py, docs/tutorials/model.rst
=> docs: tutorial: model: Mention file paths of files we're editing

CHANGELOG.md, dffml/df/base.py, dffml/df/memory.py, dffml/df/types.py, dffml/operation/dataflow.py, docs/plugins/dffml_operation.rst, tests/operation/test_dataflow.py, tests/test_df.py
=> shouldi subflow prepwork

docs/plugins/dffml_model.rst, model/scratch/dffml_model_scratch/logisticregression.py, model/scratch/setup.py, model/scratch/tests/test_lgr_integration.py
=> minor changes

.github/workflows/testing.yml
=> ci: Cache pip

CHANGELOG.md, dffml/df/base.py, dffml/df/memory.py, dffml/df/types.py, model/tensorflow/examples/tfdnnr/tfdnnr.py
=> Memory:dataflow:Cleanup in memory

CHANGELOG.md, dffml/util/cli/cmd.py
=> util: cli: FastChildWatcher windows incompatibility

model/transformers/examples/ner/test_ner_model.py
=> model: transformers: example: Fix accuracy assertion

CHANGELOG.md, dffml/source/source.py, docs/doctest_header.py
Keeping the PR short to see if I'm on the right track with the ABC.
Signed-off-by: Hashim.git <hashimchaudry23@gmail.com>
=> Source: Doctest experiment on Abstract Base Classes.

CHANGELOG.md, dffml/operation/io.py, docs/doctest_header.py
=> operation: io: Run Doctest Examples

dffml/feature/feature.py
too small a change for changelog
=> feature: Fixed failing doctest

dffml/skel/operations/Dockerfile
=> skel: operations: Add Dockerfile for HTTP service

CHANGELOG.md, dffml/operation/output.py
=> operation: output: Add GetMulti

CHANGELOG.md, configloader/png/setup.py, dffml/df/memory.py, dffml/operation/io.py, examples/shouldi/README.md, model/scratch/setup.py, model/transformers/dffml_model_transformers/ner/ner_model.py, model/transformers/examples/ner/ner_model.py, tests/df/test_async_iter.py, tests/df/test_auto_start.py
=> WIP:dataflow:Async generator operations

CHANGELOG.md, dffml/util/data.py
=> util: data: Make plugins exportable

CHANGELOG.md, dffml/base.py, dffml/util/cli/parser.py, dffml/util/data.py
=> util: cli: Use parser_helper for ParseInputsAction

CHANGELOG.md, dffml/model/slr.py, examples/model/slr/accuracy.sh, examples/model/slr/dataset.sh, examples/model/slr/predict.sh, examples/model/slr/slr.py, examples/model/slr/test_slr.py, examples/model/slr/train.sh
=> model: slr: Add example for docs

CHANGELOG.md, dffml/operation/dataflow.py, dffml/operation/mapping.py, docs/doctest_header.py
=> Added doctestable examples to mapping in operation.

dffml/operation/io.py, dffml/operation/preprocess.py
=> operations: io: Fixup examples

CHANGELOG.md, dffml/operation/model.py, docs/doctest_header.py
=> docs: operation: model_predict doctestable example

CHANGELOG.md, dffml/high_level.py
Add a load function to high_level.py which can help in loading of records from source.
closes #564
=> feature: high level: add load function

CHANGELOG.md, docs/_templates/breadcrumbs.html, scripts/docs/templates/dffml_model.rst, scripts/docs/templates/dffml_operation.rst, scripts/docs/templates/dffml_service_cli.rst, scripts/docs/templates/dffml_source.rst
=> docs: plugins: Remove 'Edit on Github' button

CHANGELOG.md, dffml/db/sql.py, dffml/db/sqlite.py, dffml/operation/db.py, docs/doctest_header.py, setup.py, tests/db/test_sqlite.py
Also
Fixes  #576  and
Fixes #577
=> Added doctestable examples to db operations

CHANGELOG.md, tests/test_noasync.py
=> tests: Added tests for noasync highlevel api

CHANGELOG.md, tests/test_high_level.py
=> tests: high_level: Added tests for load and save functions.

dffml/df/base.py
closes #189 
Signed-off-by: Sudhanshu Kumar <Sudhanshukumar5459@gmail.com>
=> df:base: create Definition for each args

CHANGELOG.md, dffml/base.py, tests/test_base.py
Fixes #522 
@pdxjohnny does this seem right? The tests gave no red flags.
=> base: Made classes with default configs to be instantiated easily.

CHANGELOG.md, model/scikit/dffml_model_scikit/scikit_base.py, model/scratch/dffml_model_scratch/logisticregression.py, model/tensorflow/dffml_model_tensorflow/dnnc.py, model/tensorflow/dffml_model_tensorflow/dnnr.py, model/tensorflow_hub/dffml_model_tensorflow_hub/text_classifier.py, model/tensorflow_hub/dffml_model_tensorflow_hub/tfhub_models.py, model/transformers/dffml_model_transformers/ner/ner_model.py
Resolves #320 
I left out a few sub-modules because I wasn't sure if they should also be dynamically imported. Please let me know if I should also push that along this PR, if you see fit.
=> model: make model plugins import third party libraries dynamically.

model/transformers/dffml_model_transformers/ner/ner_model.py
Fixes #559 
I suppose this doesn't need a changelog
=> model: transformers: ner: Change the links' formatting to rst

CHANGELOG.md, dffml/cli/list.py, tests/integration/test_cli.py, tests/test_cli.py
=> cli:list: change print to yield

docs/conf.py
dffml/docs/conf.py:92:  The app.add_javascript() is deprecated so replaced it with  app.add_js_file() .
=> fixes issue  #565

CHANGELOG.md, model/tensorflow_hub/dffml_model_tensorflow_hub/text_classifier.py, model/tensorflow_hub/examples/tfhub_text_classifier/accuracy.sh, model/tensorflow_hub/examples/tfhub_text_classifier/predict.sh, model/tensorflow_hub/examples/tfhub_text_classifier/test_data.sh, model/tensorflow_hub/examples/tfhub_text_classifier/test_textclassifier.py, model/tensorflow_hub/examples/tfhub_text_classifier/textclassifier.py, model/tensorflow_hub/examples/tfhub_text_classifier/train.sh, model/tensorflow_hub/examples/tfhub_text_classifier/train_data.sh
fix #435 
fix #537 
close #542
=> docs: model: tensorflow_hub: Add example for text classifier.

CHANGELOG.md, dffml/df/memory.py, dffml/df/types.py, dffml/operation/output.py, dffml/source/df.py, setup.py, tests/operation/test_associatedef.py, tests/source/test_df.py
=> WIP: Dataflow based Preprocessing source

examples/shouldi/shouldi/rust/analyze.py, examples/shouldi/shouldi/rust/check.py, examples/shouldi/shouldi/use.py, examples/shouldi/tests/test_cargo_audit.py, examples/shouldi/tests/test_cli_use.py
Making it `WIP` so that I can commit more subflows directly into this P.R.
=> [WIP] shouldi_subflow: added rust subflow 

CHANGELOG.md, dffml/noasync.py
=> noasync: expose run from high level to noasync

CHANGELOG.md, dffml/util/entrypoint.py, tests/util/test_entrypoint.py
=> util: entrypoint: Load supports entrypoint style relative

dffml/df/base.py
this pr will address that the self parameter will not be passed to `create_definition`.
closes #677 
=> df: base: op: handle self parameter

CHANGELOG.md, dffml/cli/dataflow.py
=> cli: dataflow: diagram: Added link on condition in dataflow graphs

CHANGELOG.md, dffml/base.py, dffml/df/types.py, dffml/source/df.py, docs/usage/mnist.rst, examples/MNIST/accuracy.sh, examples/MNIST/create_dataflow.sh, examples/MNIST/normalize.yaml, examples/MNIST/output.json, examples/MNIST/predict.sh, examples/MNIST/test_mnist.py, examples/MNIST/train.sh
Fixes: #672 
Signed-off-by: Saksham Arora sakshamarora1001@gmail.com
=> docs: usage: MNIST: Update use case to normalize image arrays

CHANGELOG.md, dffml/cli/dataflow.py, dffml/util/data.py, docs/cli.rst, docs/tutorials/operations.rst, docs/usage/dataflows.rst, docs/usage/integration.rst, docs/usage/webhook/deploy.rst, docs/usage/webhook/webhook.rst, examples/MNIST/create_dataflow.sh, examples/io/dataflow_diagram.sh, tests/integration/test_dataflow.py, tests/test_cli.py, tests/util/test_traverse.py
=> cli: dataflow: Add flow to dataflow create

CHANGELOG.md, dffml/source/op.py, setup.py, tests/source/test_op.py
=> source: op: Operation as data source

dffml/db/sqlite.py, dffml/source/file.py, tests/operation/test_sqlite_query.py, tests/secret/test_ini.py, tests/service/test_dev.py, tests/source/test_csv.py, tests/source/test_file.py, tests/test_cli.py, tests/test_record.py
#624 
All the failures are fixed but still getting some file permission errors.
=> [WIP] fix: tests: errors and failures on Windows 

CHANGELOG.md, dffml/cli/list.py, dffml/cli/ml.py, dffml/record.py, dffml/util/data.py, dffml/util/display.py
Fixes: #612 
Fixes: #335 
```console
dffml predict all \
-model tfdnnc \
-model-batchsize 1000 \
-model-hidden 30 50 25 \
-model-clstype int \
-model-predict label:int:1 \
-model-classifications $(seq 0 9) \
-model-features image:int:$((28 * 28)) \
-sources images=csv \
-source-filename image.csv  \
-source-loadfiles image  \
-pretty
-log debug
```
Example output of 1 of the records:
```console
Key:	four
Record Features
+----------------------------------------------------------------------------------------------------------------------------------------------+
|               image               |                 0,0,0,0,0,0,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,... (length:784)                 |
+------------------------------------------------------------------------------------- …
```
=> record: Improve string representation

configloader/png/dffml_config_png/configloader.py, configloader/yaml/dffml_config_yaml/configloader.py, dffml/base.py, dffml/configloader/json.py, dffml/service/dev.py
=> service: dev: Rename config to configloader

model/scikit/dffml_model_scikit/scikit_base.py, model/scikit/dffml_model_scikit/scikit_models.py
=> model: scikit: remove applicable features and pandas

CHANGELOG.md, dffml/source/csv.py
Fixes: #716 
Signed-off-by: sakshamarora1 <sakshamarora1001@gmail.com>
=> source: csv: Update csv source to not overwrite configloaded data to every row

CHANGELOG.md, docs/tutorials/operations.rst, examples/shouldi/shouldi/python/pypi.py
=> examples: shouldi: python: pypi: Update definition for directory input

model/transformers/dffml_model_transformers/qa/qa_model.py, model/transformers/examples/qa/accuracy.sh, model/transformers/examples/qa/predict.sh, model/transformers/examples/qa/train.sh, model/transformers/tests/test_classification_model.py, model/transformers/tests/test_qa_integration.py, model/transformers/tests/test_qa_model.py
=> model: transformers: qa: Change default logging dir of SummaryWriter

model/transformers/dffml_model_transformers/classification/classification_model.py, model/transformers/dffml_model_transformers/ner/ner_model.py, model/transformers/setup.py
=> model: transformers: Add support for transformers 3.0.0

CHANGELOG.md, dffml/high_level.py, dffml/model/model.py, dffml/model/slr.py, dffml/operation/model.py, dffml/skel/model/REPLACE_IMPORT_PACKAGE_NAME/myslr.py, docs/tutorials/models/slr.rst, model/autosklearn/dffml_model_autosklearn/config.py, model/daal4py/dffml_model_daal4py/daal4pylr.py, model/scikit/dffml_model_scikit/scikit_base.py, model/scikit/tests/test_scikit.py, model/scratch/dffml_model_scratch/logisticregression.py, model/tensorflow/dffml_model_tensorflow/dnnc.py, model/tensorflow/dffml_model_tensorflow/dnnr.py, model/tensorflow_hub/dffml_model_tensorflow_hub/text_classifier.py, model/tensorflow_hub/tests/test_model.py, model/transformers/dffml_model_transformers/classification/classification_model.py, model/transformers/dffml_model_transformers/ner/ner_model.py, model/transformers/dffml_model_transformers/qa/qa_model.py, model/transformers/tests/test_ner_model.py, model/vowpalWabbit/dffml_model_vowpalWabbit/vw_base.py, model/vowpalWabbit/tests/test_vw.py, service/http/dffml_service_http/routes.py, service/http/dffml_service_http/util/testing.py, tests/test_cli.py
=> dffml: models: Predict method should take source context

CHANGELOG.md, dffml/cli/dataflow.py, docs/usage/dataflows.rst, docs/usage/webhook/deploy.rst, examples/MNIST/create_dataflow.sh, examples/MNIST/create_dataflow_1.sh, tests/df/test_df_create.py
=> cli: dataflow: create: Add ability to specify instance names of operations

model/transformers/dffml_model_transformers/classification/classification_model.py, model/transformers/dffml_model_transformers/ner/ner_model.py, model/transformers/setup.py
=> model: transformers: Support transformers 3.0.2

CHANGELOG.md, dffml/plugins.py, dffml/service/dev.py, tests/service/test_dev.py
=> service: dev: install: Usability enchancements

dffml/accuracy/accuracy.py, dffml/accuracy/mse.py, dffml/model/model.py, dffml/model/slr.py, examples/accuracy/mse/dataset.sh, examples/accuracy/mse/mse.py, examples/accuracy/mse/test_mse.py, scripts/docs/care
=> examples: accuracy: Add the mse accuracy plugin example and test

docs/usage/webhook/webhook.rst, examples/ffmpeg/deploy/webhook/mc/http/webhook.yaml
=> docs:examples:ffmpeg: Add immediate response to webhook receiver

model/autosklearn/dffml_model_autosklearn/config.py, model/daal4py/dffml_model_daal4py/daal4pylr.py, model/scikit/dffml_model_scikit/scikit_base.py, model/scratch/dffml_model_scratch/logisticregression.py, model/tensorflow/dffml_model_tensorflow/dnnc.py, model/tensorflow/dffml_model_tensorflow/dnnr.py, model/tensorflow_hub/dffml_model_tensorflow_hub/text_classifier.py, model/tensorflow_hub/dffml_model_tensorflow_hub/text_classifier_accuracy.py, model/transformers/dffml_model_transformers/classification/classification_model.py, model/transformers/dffml_model_transformers/ner/ner_model.py, model/transformers/dffml_model_transformers/qa/qa_model.py, model/vowpalWabbit/dffml_model_vowpalWabbit/vw_base.py
=> dffml: model: Update the accuracy method from the models

CHANGELOG.md, dffml/util/data.py
Fixes: #822
Signed-off-by: sakshamarora1 <sakshamarora1001@gmail.com>
=> util: data: export_value now converts numpy array to JSON serializable datatype

model/pytorch/dffml_model_pytorch/pytorch_base.py, model/spacy/dffml_model_spacy/ner/ner_model.py, model/xgboost/dffml_model_xgboost/xgbregressor.py
=> model: Update the spacy, pytorch, xgboost models

CHANGELOG.md, dffml/base.py, dffml/util/cli/arg.py, dffml/util/cli/cmd.py, model/tensorflow/tests/test_dnnc.py, model/tensorflow/tests/test_dnnr.py, service/http/tests/test_routes.py, tests/df/test_memory.py, tests/source/test_csv.py, tests/source/test_file.py, tests/test_base.py, tests/util/model-config.yaml, tests/util/test_cli.py
base: Update config classmethod in BaseConfigurable class
Signed-off-by: sakshamarora1 <sakshamarora1001@gmail.com>
=> util: cli: arg: Add configloading ability to parse_unknown

model/autosklearn/dffml_model_autosklearn/config.py, model/autosklearn/setup.py
- Remove the shared_mode config property
- Bump the version to 0.10.0
closes #858 
=> model: autosklearn: Bump the version to 0.10.0

.ci/deps.sh, .ci/dffml-install.sh, .ci/run.sh, .github/workflows/testing.yml, dffml/skel/common/setup_common.py, docs/_ext/consoletest.py, docs/examples/integration.rst, docs/examples/shouldi.rst, docs/installation.rst, docs/tutorials/dataflows/nlp.rst, docs/tutorials/models/iris.rst, docs/tutorials/models/package.rst, docs/tutorials/models/slr.rst, docs/tutorials/sources/complex.rst, docs/tutorials/sources/file.rst, examples/shouldi/requirements.txt, examples/shouldi/setup_common.py, examples/shouldi/setup_console_scripts.py, examples/source/setup.py, examples/source/test_custom_sqlite.py, tests/docs/test_consoletest.py
```console
$ diff -y <(git grep code-block -- docs/ | awk '{print $1}' | sed 's/:.*//' | sort | uniq) <(git grep :test: -- docs/ | awk '{print $1}' | 
sed 's/:.*//' | sort | uniq)
docs/cli.rst                                                  <
docs/concepts/index.rst                                       <
docs/contributing/codebase.rst                                <
docs/contributing/debugging.rst                               <
docs/contributing/dev_env.rst                                 <
docs/contributing/docs.rst                                    <
docs/contributing/editors/vscode.rst                          <
docs/contributing/git.rst                                     <
docs/contributing/maintainers.rst                             <
docs/contributing/style.rst …
```
=> tests: docs: tutorials: Test tutorials

model/spacy/dffml_model_spacy/ner/ner_model.py, model/spacy/examples/ner/accuracy.sh, model/spacy/examples/ner/predict.sh, model/spacy/examples/ner/train.sh, model/spacy/tests/test_ner_integration.py, model/spacy/tests/test_ner_model.py, model/transformers/dffml_model_transformers/classification/classification_model.py, model/transformers/dffml_model_transformers/ner/ner_model.py, model/transformers/dffml_model_transformers/qa/qa_model.py, model/transformers/examples/classification/accuracy.sh, model/transformers/examples/classification/predict.sh, model/transformers/examples/classification/train.sh, model/transformers/examples/ner/accuracy.sh, model/transformers/examples/ner/ner_model.py, model/transformers/examples/ner/predict.sh, model/transformers/examples/ner/train.sh, model/transformers/examples/qa/accuracy.sh, model/transformers/examples/qa/predict.sh, model/transformers/examples/qa/train.sh, model/transformers/tests/test_classification_integration.py, model/transformers/tests/test_classification_model.py, model/transformers/tests/test_ner_integration.py, model/transformers/tests/test_ner_model.py, model/transformers/tests/test_qa_integration.py, model/transformers/tests/test_qa_model.py
=> plugins: models: Update 'output_dir' -> 'directory'

.github/workflows/testing.yml, dffml/plugins.py
=> ci: Don't skip model/vowpalwabbit

examples/flower17/pytorch-alexnet/layers.yaml, examples/rockpaperscissors/model.yaml, model/pytorch/dffml_model_pytorch/utils/utils.py
solved issue #908.
Also changed the model example in docs.
=> model: pytorch: Change network layer name property to layer_type

model/xgboost/dffml_model_xgboost/xgbregressor.py, model/xgboost/tests/test_model.py
=> model: xgboost: Add console example

docs/tutorials/neuralnetwork.rst, examples/rockpaperscissors/model.yaml, examples/rockpaperscissors/python_example.py, model/pytorch/dffml_model_pytorch/pytorch_base.py, model/pytorch/dffml_model_pytorch/pytorch_net.py
Fixes: #907 
Signed-off-by: sakshamarora1 sakshamarora1001@gmail.com
=> docs: tutorials: neuralnetwork: Added useful explanations and fixed code in pytorch plugin

service/http/dffml_service_http/api.js, service/http/dffml_service_http/cli.py, service/http/dffml_service_http/routes.py, service/http/dffml_service_http/util/testing.py, service/http/docs/api.rst, service/http/docs/cli.rst, service/http/examples/javascript/index.js, service/http/tests/test_cli.py, service/http/tests/test_routes.py
Update HTTP Services to understand the accuracy scorers
Addresses #732
Signed-off-by: Sudhanshu Sudhanshukumar5459@gmail.com
=> WIP: Phase6: Update the HTTP Service

examples/rockpaperscissors/python_example.py, model/pytorch/dffml_model_pytorch/__init__.py, model/pytorch/dffml_model_pytorch/pytorch_base.py, model/pytorch/dffml_model_pytorch/pytorch_pretrained.py, model/pytorch/examples/resnet18/accuracy.sh, model/pytorch/examples/resnet18/layers.yaml, model/pytorch/examples/resnet18/predict.sh, model/pytorch/examples/resnet18/train.sh, model/pytorch/tests/test_resnet18.py
Fixes: #995 
Signed-off-by: sakshamarora1 <sakshamarora1001@gmail.com>
=> model: pytorch: Fix tests and update code and documentation

model/scikit/dffml_model_scikit/scikit_base.py
=> model: scikit: NameError bug

CHANGELOG.md, dffml/record.py, model/daal4py/tests/test_lr.py, model/scratch/tests/test_lgr.py, model/scratch/tests/test_slr.py
=> Added: Force key to be string on init

dffml/df/base.py
=> Add `valid_return_none` argument to @op

docs/contributing/gsoc/2021.md
added the link as provided in #1014
=> added rubric page link

docs/tutorials/models/package.rst
=> Spell Error Corrected

dffml/source/csv.py
=> source: csv: Strip spaces in columns by default

CHANGELOG.md, configloader/image/tests/test_config.py, dffml/cli/dataflow.py, dffml/df/memory.py, dffml/model/model.py, dffml/util/crypto.py, dffml/util/file.py, model/scikit/dffml_model_scikit/scikit_base.py, model/tensorflow/dffml_model_tensorflow/dnnc.py, model/tensorflow_hub/dffml_model_tensorflow_hub/text_classifier.py, model/vowpalWabbit/dffml_model_vowpalWabbit/vw_base.py, tests/source/test_idx.py, tests/test_ci.py
=> util: crypto: Create secure_hash and insecure_hash functions

CHANGELOG.md, dffml/util/log.py, dffml/util/net.py
* This PR addresses issue #1058 
* It is ready for review 
* All tests are passing locally and only one is failing in CI which is `LGTM analysis: Python`.
=> util: net: cached_download(): Changed logging mechanism to log only on 1% changes

CHANGELOG.md, dffml/service/dev.py, dffml/util/net.py, examples/or_covid_data_by_county.py, examples/shouldi/tests/binaries.py, examples/shouldi/tests/test_cargo_audit.py, examples/shouldi/tests/test_cli_use.py, examples/shouldi/tests/test_dependency_check.py, examples/shouldi/tests/test_golangci_lint.py, examples/shouldi/tests/test_npm_audit.py, examples/source/dataset/base/dataset_source/my_training.py, examples/source/dataset/base/dataset_source/my_training_run.py, model/pytorch/tests/test_pytorchnet.py, model/pytorch/tests/test_resnet18.py, tests/source/test_idx.py, tests/util/test_net.py
=> util: net: Change cached_download and derivatives to functions.

.ci/deps.sh, .gitignore, CHANGELOG.md, docs/conf.py, docs/contributing/docs.rst, docs/examples/index.rst, docs/examples/notebooks/index.rst, docs/examples/notebooks/moving_between_models.nblink, examples/notebooks/moving_between_models.ipynb, requirements-dev.txt, tests/notebooks/test_moving_between_models.py
Was waiting on #1092 (merged now)
=> WIP: examples: notebooks: Moving between models

.github/workflows/testing.yml, CHANGELOG.md, docs/examples/icecream_sales.rst, docs/examples/index.rst, examples/dataflow/icecream_sales/dataset.csv, examples/dataflow/icecream_sales/main.py, examples/dataflow/icecream_sales/operations.py, examples/dataflow/icecream_sales/test_dataset.csv
Addresses #599 
Signed-off-by: Sudhanshu Sudhanshukumar5459@gmail.com
=> examples: dataflow: Add Icecream sales demo

examples/flower17/sklearn-opencv/accuracy.sh, model/scikit/dffml_model_scikit/__init__.py, model/scikit/dffml_model_scikit/scikit_base.py, model/scikit/dffml_model_scikit/scikit_model_scorer.py, model/scikit/setup.py, model/scikit/tests/test_scikit.py
Signed-off-by: Sudhanshu Sudhanshukumar5459@gmail.com
=> model: scikit: scorer: Add sklearn model accuracy scorer 

dffml/model/model.py
Related: #1107 
Signed-off-by: Jayant Singh <mrsinghj9@gmail.com>
=> dffml: model: Fixed spelling error in comment.

dffml/df/types.py, dffml/operation/archive.py, dffml/operation/compression.py
* Fixes: #1159 
* Fixes: #1160
=> operation : Add operation output for archive and compression

CHANGELOG.md, docs/examples/notebooks/index.rst, docs/examples/notebooks/saving_and_loading_models.nblink, examples/notebooks/saving_and_loading_models.ipynb
Signed-off-by: mHash1m <hashimchaudry23@gmail.com>
=> examples: notebooks: Create usecase example notebook 'Saving and loading models'

CHANGELOG.md, docs/examples/notebooks/ensemble_by_stacking.nblink, docs/examples/notebooks/index.rst, examples/notebooks/ensemble_by_stacking.ipynb
- Using 2 models instead of 4.
- Accuracy for ensembling 2 models as suggested didn't turn out great.
- Removed the accuracies part to keep the notebook precise.
- Showing final predictions instead of ensemble accuracy comparison, requires `stacked_test_predictions` either way.
**Update**
- Fixed Accuracy
- Added Visualizations
Signed-off-by: mHash1m <hashimchaudry23@gmail.com>
=> examples: notebooks: Create usecase example notebook 'Ensemble by stacking'

CHANGELOG.md, dffml/optimizer/__init__.py, dffml/optimizer/optimizer.py, dffml/optimizer/parameter_grid.py, docs/examples/notebooks/index.rst, docs/examples/notebooks/tuning_models.nblink, docs/plugins/index.rst, examples/notebooks/ensemble_by_stacking.ipynb, examples/notebooks/tuning_models.ipynb, model/xgboost/dffml_model_xgboost/xgbclassifier.py, scripts/docs/templates/dffml_optimizer.rst, setup.py
=> examples: notebooks: Add usecase example, for 'Tuning Models', and Optimizer ParameterGrid.

.gitignore, dffml/operation/archive.py
* Fixes: #1198 
* Partially FIxes: #662
=> operation: archive: patched to preserve dir structure

.ci/run.sh, .github/workflows/testing.yml, CHANGELOG.md, dffml/service/dev.py, dffml/source/dfpreprocess.py, operations/data/dffml_operations_data/operations.py, requirements-dev.txt, tests/service/test_dev.py
=> ci: Lint unused imports

CHANGELOG.md, dffml/tuner/__init__.py, dffml/tuner/parameter_grid.py, dffml/tuner/tuner.py, docs/plugins/index.rst, examples/notebooks/tuning_models.ipynb, scripts/docs/templates/dffml_optimizer.rst, scripts/docs/templates/dffml_tuner.rst, setup.py
* Fixes: #1200 
* Ready for review: @pdxjohnny 
* All CI tests passing ✅
=> tuner: Renamed `Optimizer` to `Tuner`

CHANGELOG.md, dffml/cli/cli.py, dffml/source/df.py, dffml/source/dfold.py, dffml/source/dfpreprocess.py, docs/cli.rst, docs/examples/data_cleanup/data_cleanup.rst, docs/examples/data_cleanup/data_cleanup_classfication.rst, docs/examples/flower17/flower17_scikit.rst, docs/examples/icecream_sales.rst, docs/examples/integration.rst, docs/examples/mnist.rst, docs/tutorials/dataflows/nlp.rst, examples/MNIST/accuracy.sh, examples/MNIST/predict.sh, examples/MNIST/train.sh, examples/dataflow/icecream_sales/main.py, examples/flower17/sklearn-opencv/accuracy.sh, examples/flower17/sklearn-opencv/predict.sh, examples/flower17/sklearn-opencv/train.sh, examples/maintained/predict.sh, examples/maintained/train.sh, examples/nlp/accuracy.sh, examples/nlp/predict.sh, examples/nlp/sklearn/accuracy.sh, examples/nlp/sklearn/predict.sh, examples/nlp/sklearn/train.sh, examples/nlp/train.sh, setup.py, tests/source/test_df.py
Signed-off-by: Sudhanshu Sudhanshukumar5459@gmail.com
=> Rename df to dfpreprocess and dfpreprocess to df

README.md, docs/about.rst
* Updated mission statement as discussed on gitter
* It is ready for review and merge
=> docs: Updated Mission Statement

CHANGELOG.md, dffml/high_level/ml.py, dffml/util/internal.py, tests/test_high_level.py
fixes #1222 
Signed-off-by: Hashim Chaudry <hashimchaudry23@gmail.com>
=> high_level: Accept lists for data arguments in train, score and predict

dffml/util/python.py
=> util: python: within_method: Do not monkeypatch inspect.findsource on Python greater than 3.7

README.md
Renders dark/light mode logos depending on user's mode.
=> Issue #1305

docs/contributing/gsoc/2022/index.rst
'Begineer' corrected to 'Beginner'.
=> Fixed spelling

docs/contributing/gsoc/2022/index.rst
* Ready to merge
* Ping: @pdxjohnny
=> docs: contributing: gsoc: 2022: Added link to GSoC talk

docs/contributing/git.rst
Documentation added related how to rebase in branches in contributing/git.
=> Rebasing in changes #1340

entities/alice/alice/please/contribute/recommended_community_standards/recommended_community_standards.py
=> Alice: fix missing import

entities/alice/alice/please/contribute/recommended_community_standards/recommended_community_standards.py, entities/alice/alice/shouldi/contribute/cicd.py
alice: Added method to fetch Groovy function list
=> alice: Added method to fetch Groovy function list

operations/innersource/dffml_operations_innersource/npm_groovy_lint.py
Related: https://github.com/intel/dffml/issues/1435
=> operations: innersource: npm groovy lint: code narc server: Include only groovy files

configloader/jsonschema/README.rst
=> configloader: jsonschema: README: Remove pip install

.github/workflows/alice_async_comms.yml
Related: https://github.com/peter-evans/create-pull-request/issues/2790
=> ci: alice: async: comms: Update create-pull-request to v6.0.2

operations/nlp/dffml_operations_nlp/tools/pgvector.py
- **operations: nlp: tools: pgvector: LangGraph Agenic RAG**
- **operations: nlp: tools: pgvector: Loading DFFML docs to chroma**
=> langgraph pgvector

operations/nlp/dffml_operations_nlp/tools/dffml_docs.py
Asciinema: https://asciinema.org/a/653113
=> operations: nlp: tools: dffml docs: Write a whitepaper on the Open Architecture

operations/nlp/dffml_operations_nlp/tools/dffml_docs.py
=> operations: nlp: tools: dffml docs: ParentDocumentRetriever until no parent_id

.github/workflows/alice_async_comms.yml, .github/workflows/dffml_build_images_containers.yml, .github/workflows/dispatch_build_images_containers.yml, .github/workflows/testing.yml
=> best practices: ossf scorecard: Fix token permissions

scripts/ossf_scorecard_pindeps.py
=> scripts: ossf scorecard pindeps: docs: Add usage
